#! /usr/bin/env ruby

require 'rock/bundles'

Bundles.initialize

task_name  = ARGV.shift

Bundles.run \
    'bus_schremote::Task'   => 'bus',
    'inclinometer::Task' => task_name do

    bus  = Bundles.get 'bus'
    task = Bundles.get task_name

    # Configure the bus driver first, we need it to connect the micron
    bus.configure
    Orocos.log_all

    bus.start

    # Connect the micron to the bus
    bus.port(task_name).connect_to task.analog_input, :type => :buffer, :size => 50
    task.configure
    # task.start

    Bundles.watch(bus, task)
end



