#! /bin/sh
killall -9 orogen_default_bus_schremote__Task
killall -9 orogen_default_inclinometer__Task
killall -9 orogen_default_pressure_velki__Task
killall -9 orogen_default_sonar_tritech__Micron
killall -9 orogen_default_sonar_tritech__Profiling
killall -9 orogen_default_ptu_kongsberg_oe10__Task
killall -9 orogen_default_transformer__Task
killall -9 ruby1.9.1
ps ax | grep orogen | grep -v grep
