#! /usr/bin/env ruby

require 'rock/bundles'
require 'orocos/async'

Bundles.initialize

def connect_device_to_bus(bus, task)
    task_name = task.basename
    task.io_port = ""
    bus.port(task_name).connect_to task.io_raw_in, :type => :buffer, :size => 50
    task.io_raw_out.connect_to bus.port("w#{task_name}"), :type => :buffer, :size => 50
end

def restart_on_exception(task)
    task.to_async.on_state_change do |state|
        if !task.runtime_state?(state)
            begin
                if task.exception_state?(state)
                    task.reset_exception
                    task.configure
                    task.start
                elsif task.rtt_state == :PRE_OPERATIONAL
                    task.configure
                    task.start
                elsif task.rtt_state == :STOPPED
                    task.start
                end
            rescue Orocos::StateTransitionFailed
            end
        end
    end
end

Bundles.run \
    'bus_schremote::Task' => ['bus1', 'bus2'],#'busses',
    'inclinometer::Task' => ['inclination_right', 'inclination_body', 'inclination_key'],
    'pressure_velki::Task' => 'pressure',
    'ptu_kongsberg_oe10::Task' => 'ptu',
    'sonar_tritech::Micron' => 'micron',
    'sonar_tritech::Profiling' => 'seaking' do # , => :output '%m-%p.log', :valgrind => ['pressure','bus1']

    bus1   = Bundles.get 'bus1'
    Orocos.conf.apply bus1, ['default', "blue1"]
    bus2   = Bundles.get 'bus2'
    Orocos.conf.apply bus2, ['default', "blue2"]

# Configure the bus driver first, we need it to connect the micron
    bus1.configure
    bus2.configure
    Orocos.log_all

    bus1.start
    bus2.start

    inclination_body = Bundles.get 'inclination_body'
    bus2.inclination_body.
	connect_to inclination_body.analog_input
    Orocos.conf.apply inclination_body, ['default', 'roll']
    inclination_body.configure
    inclination_body.start

    inclination_body_2 = Bundles.get 'inclination_body_2'
    bus2.inclination_body_2.
	connect_to inclination_body_2.analog_input
    Orocos.conf.apply inclination_body_2, ['default', 'pitch']
    inclination_body_2.configure
    inclination_body_2.start

    pressure = Bundles.get 'pressure'
    restart_on_exception(pressure)
    connect_device_to_bus(bus1, pressure)
    pressure.configure
    pressure.start

    ptu = Bundles.get 'ptu'
    restart_on_exception(ptu)
    connect_device_to_bus(bus2, ptu)
    ptu.configure
    ptu.start



    micron = Bundles.get 'micron'
    seaking = Bundles.get 'seaking'

    if bus2.has_port?('micron')
	restart_on_exception(micron)
        connect_device_to_bus(bus2, micron)
        #micron.configure
        #micron.start
    else
	restart_on_exception(seaking)
        connect_device_to_bus(bus2, seaking)
        #seaking.configure
        #seaking.start
    end

    Bundles.transformer.setup(pressure, inclination_body, ptu, seaking)

    Bundles.watch(
        bus1, bus2, inclination_body,inclination_body_2, 
        pressure, micron, seaking, ptu
    ) do
	# Workaround bug in orocos.rb to get the on_state_change in restart_on_exception working
	Orocos::Async.event_loop.step
    end
end

