--- name:default
digital_ins:
    - pin: 10
      type: PIN_DIN_PULLUP
      name: inductive1
    - pin: 11
      type: PIN_DIN_PULLUP
      name: inductive2
uarts:
    - name: micron
      mode: 0
      # The electronics has trouble with 115200, switch back to a slower
      # baudrate
      baud: 9600
      uart_module: 0
      tx: 8
      tx_type: PIN_DOUT_HIGH
      rx: 2
digital_outs: []
ip: '192.168.1.255'
mac: '00:04:A3:31:00:14'
port: 3101
