--- name:default
# x cell resolution in meter
cell_resolution_x: 0.05
# y cell resolution in meter
cell_resolution_y: 0.05
# enter a path if the environment should be saved
envire_path: ''
# update period in s for the envire_data port.
envire_period: 0
# true if laser scan should be filtered
filter_laserscan: false
# x size of the grid in meter
grid_size_x: 20.0
# y size of the grid in meter
grid_size_y: 20.0
# the global name that should be used for the internal laser frame
laser_frame: laser
# Time in s between laserscan readings
laserscan_period: 0.4
# filter: bounding box of the sensor in meter
sensor_bounding_box: 0
# uncertainty of the laser scan
sensor_uncertainty: 0.017453293
# show an elevation grid instead of a pointcloud
show_elevation_grid: false
# show a mls grid instead of a pointcloud
show_mls_grid: true
# list of static transformations
static_transformations: []
# surfaces that are used to display the data
surface_count: 1
# known distance to the surface to scan, zero means distance is unknown
surface_distance: 0.0
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 3.0
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 0

use_stop_log: false
# the global name that should be used for the internal world frame
world_frame: world
