--- name:default
# This is reset to an empty string in the run script when connected to the bus
io_port: 'serial:///dev/ttyUSB0:9600'
device_id: 2
# the timeout on read. Defaults to one second
io_read_timeout:
  microseconds: 1000000
# the interval at which the status port should be written. Defaults to one second
io_status_interval:
  microseconds: 1000000
# the timeout on write. Defaults to one second. Used only in direct I/O mode
io_write_timeout:
  microseconds: 1000000

pan_plate_frame: ptu_pan_plate
tilt_plate_frame: ptu_tilt_plate

use_end_stops: false

limits:
  names:
  - pan
  - tilt
  elements:
  - min:
      position: 0.35 # 20 degrees. The PTU gets in a weird state below that
      speed: .nan
      effort: .nan
      raw: .nan
    max:
      position: 4.71238898038469 # 270 degrees
      speed: 0.9
      effort: .nan
      raw: .nan
  - min:
      position: 0.35 # 20 degrees. The PTU gets in a weird state below that
      speed: .nan
      effort: .nan
      raw: .nan
    max:
      position: 4.71238898038469
      speed: 0.9
      effort: .nan
      raw: .nan

