--- name:default
# The device address. It can either be serial://PATH[:baudrate],
# udp://IP_OR_HOSTNAME[:PORT] or tcp://IP_OR_HOSTNAME[:PORT]. Leave empty if
# you mean to use the io_raw_in and io_raw_out ports.
io_port: 'serial:///dev/ttyS0:19200'
# The timeout on read. Defaults to one second
io_read_timeout:
  microseconds: 1000000
# The interval at which the status port should be written. Defaults to one
# second
io_status_interval:
  microseconds: 1000000
# The timeout on write. Defaults to one second. Used only in direct I/O mode
io_write_timeout:
  microseconds: 1000000
# no documentation available for this property
sensor_frame: world_inclinometer_roll
# no documentation available for this property
world_frame: surface
