--- name:default
# the device address. It can either be serial://PATH[:baudrate], udp://IP_OR_HOSTNAME[:PORT] or tcp://IP_OR_HOSTNAME[:PORT]. Leave empty if you mean to use the io_raw_in and io_raw_out ports.
io_port: 'serial:///dev/ttyUSB0:9600'

acquisition_timeout:
  microseconds: 1000000

config:
  left_limit:
      rad: 1.65
  right_limit:
      rad: -1.65
  angular_resolution:
    rad: 0.00393
  select_channel: 1
  frequency_chan1: 600000
  frequency_chan2: 1200000
  max_distance: 2.5
  min_distance: 0.3
  speed_of_sound: 1500.0
  gain: 0.2
  filt_gain: 0.01
  continous: true

configure_timeout: 20.0
# the timeout on read. Defaults to one second
io_read_timeout:
  microseconds: 20000000
# the interval at which the status port should be written. Defaults to one second
io_status_interval:
  microseconds: 1000000
# the timeout on write. Defaults to one second. Used only in direct I/O mode
io_write_timeout:
  microseconds: 2000000
